### ISSUE TITLE
crash on TS-264

### ISSUE THREAD

**Issue by McSim85** [pedropombeiro/qnapexporter#3]
Hey hey,

Thanks for developing such a nice exporter.
It seems like the exporter crashes when I open the page http://192.168.88.23:9094/metrics

```
./qnapexporter
2023/10/19 09:28:52 Listening to HTTP requests at :9094
2023/10/19 09:29:00 Reading environment...
2023/10/19 09:29:00 Hostname: MEDIA, err=<nil>
2023/10/19 09:29:00 Retrieving QTS version
2023/10/19 09:29:00 Retrieved getsysinfo path: "/sbin/getsysinfo"
2023/10/19 09:29:00 Retrieved sysdhnum: 4
2023/10/19 09:29:00 Retrieved sysfannum: 1
2023/10/19 09:29:00 Retrieved volCount: 4
2023/10/19 09:29:00 Retrieved vol_desc "[Volume SSD, Pool 1]", parsed to "SSD"
2023/10/19 09:29:00 Retrieved volume "SSD" vol_fs "EXT4"
2023/10/19 09:29:00 Retrieved volume "SSD" vol_totalsize "532.82 GB"
2023/10/19 09:29:00 Retrieved volume "SSD" vol_status "Ready"
2023/10/19 09:29:00 Retrieved vol_desc "[Volume backups, Pool 2]", parsed to "backups"
2023/10/19 09:29:01 Retrieved volume "backups" vol_fs "EXT4"
2023/10/19 09:29:01 Retrieved volume "backups" vol_totalsize "990.60 GB"
2023/10/19 09:29:01 Retrieved volume "backups" vol_status "Ready"
2023/10/19 09:29:01 Retrieved vol_desc "[Volume Volume, Pool 2]", parsed to "Volume"
2023/10/19 09:29:01 Retrieved volume "Volume" vol_fs "EXT4"
2023/10/19 09:29:01 Retrieved volume "Volume" vol_totalsize "1.01 TB"
2023/10/19 09:29:01 Retrieved volume "Volume" vol_status "Ready"
2023/10/19 09:29:01 Retrieved vol_desc "[Volume Family, Pool 2]", parsed to "Family"
2023/10/19 09:29:01 Retrieved volume "Family" vol_fs "EXT4"
2023/10/19 09:29:01 Retrieved volume "Family" vol_totalsize "3.48 TB"
2023/10/19 09:29:02 Retrieved volume "Family" vol_status "Ready"
2023/10/19 09:29:02 Found volumes [{0 EXT4 SSD Ready 0 5.7211111866368e+11} {1 EXT4 backups Ready 0 1.0636486508544e+12} {2 EXT4 Volume Ready 0 1.11050674405376e+12} {3 EXT4 Family Ready 0 3.82630046466048e+12}]
2023/10/19 09:29:02 Retrieved sysvolinfo
2023/10/19 09:29:02 Retrieved hal_app path: "/sbin/hal_app"
2023/10/19 09:29:02 Retrieving QM2 enclosures
2023/10/19 09:29:02 Retrieving network interfaces in "/sys/class/net"...
2023/10/19 09:29:02 Retrieving devices in "/dev"...
2023/10/19 09:29:02 Found devices: [nvme0n1 nvme1n1 sda sdb]
2023/10/19 09:29:02 Retrieving dm-cache devices...
2023/10/19 09:29:02 Found cache clients: [vg1-tp1_tierdata_2 vg2-tp2_tierdata_2]
2023/10/19 09:29:02 Found cache volumes: [vg256-lv256	(253:3)]
2023/10/19 09:29:02 Connecting to UPS daemon
panic: runtime error: index out of range [1] with length 1

goroutine 113 [running]:
github.com/pedropombeiro/qnapexporter/lib/exporter/prometheus.(*promExporter).getDmCacheStatsMetrics(0xc000320540)
	/github/workspace/lib/exporter/prometheus/disk.go:108 +0x545
github.com/pedropombeiro/qnapexporter/lib/exporter/prometheus.fetchMetricsWorker(0xc000043690?, 0xc0000437d0?, 0xd, 0xc000154c60?)
	/github/workspace/lib/exporter/prometheus/prometheus.go:166 +0x78
created by github.com/pedropombeiro/qnapexporter/lib/exporter/prometheus.(*promExporter).WriteMetrics
	/github/workspace/lib/exporter/prometheus/prometheus.go:126 +0x1fc
```
QNAP model is TS-264
<img width="636" alt="image" src="https://github.com/pedropombeiro/qnapexporter/assets/32900310/0330533c-9845-4442-8c00-9ea842ec3583">

**Comment by SkyeYoung** [comment]
I also encountered this problem. After looking at the code, it seems that the returned data is somewhat different on different devices.

https://github.com/pedropombeiro/qnapexporter/blob/7d7a127c7dd5841f5beb2f84d95267cdf3d0803f/lib/exporter/prometheus/disk.go#L88-L111

Here the string with index 3 is taken directly, but it seems that on my device it should be 4

<img width="1000" alt="image" src="https://github.com/pedropombeiro/qnapexporter/assets/48400568/1ad57089-c17d-440d-ba10-0d1c3fe474ac">

**Comment by SkyeYoung** [comment]
I've pushed a PR to try to fix this, maybe you can also try compiling one yourself and give it a try.

**Comment by pedropombeiro** [comment]
Sorry for the long silence on this issue, I missed the notification (I wasn't even aware other people were using this project, it's nice to know that others are benefitting from this exporter 🙂)
